### PR TITLE
removed landingpage tutorial

### PR DESCRIPTION
**Pull request by Sieuwkje-firely**
Removed landingpage tutorial as this is no longer working. Tutorial needs to be updated, but in the meantime it is better to remove it from the public eye, since it is not certain when and if it is possible to get it to work again.

### CODE REVIEW

**Review by cknaap — CHANGES_REQUESTED** [review]
This page is listed on several places so you need to remove it there as well:
- plugins.rst
- plugins_configclasses.rst
- available_plugins.rst

Then build the docs and check for any warnings on missing references.

**Comment by alexzautke** [comment]
@richfirely Didn't you fix the plugin some time last year?

**Comment by richfirely** [comment]
@alexzautke No. It was inconsistent with NET3.0 and then not working at all with NET60 (at the time). It needs to be rewritten in NET60 using razor pages rather than MVC. Better to remove until we have time for that.

**Comment by Sieuwkje-firely** [comment]
@cknaap, I removed all the links I could find. Could you check again?

**Comment by Sieuwkje-firely** [comment]
> This page is listed on several places so you need to remove it there as well:
> 
>     * plugins.rst
> 
>     * plugins_configclasses.rst
> 
>     * available_plugins.rst
> 
> 
> Then build the docs and check for any warnings on missing references.

Done

**Comment by cknaap** [comment]
Hi @Sieuwkje , I see you already merged it. All right for now, but usually, the reviewer should approve the applied changes first.

**Pull request merged**
